question_data = [{"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard "
                              "Mark II computer.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "The programming language &quot;Python&quot; is based off a modified version of "
                              "&quot;JavaScript&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "The logo for Snapchat is a Bell.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "Pointers were not used in the original C programming language; they were added later "
                              "on in C++.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "&quot;HTML&quot; stands for Hypertext Markup Language.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "Android versions are named in alphabetical order.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, "
                              "Android, and Chrome OS.",
                  "correct_answer": "False", "incorrect_answers": ["True"]}]
